assistant_name: "0.5acc_overconfident"
assistant_correctness:
  distribution_name: "bernoulli"
  params:
    p: 0.5
confidence_when_correct:
  distribution_name: "beta"
  params:
    a: 6
    b: 2
confidence_when_incorrect:
  distribution_name: "beta"
  params:
    a: 4
    b: 2
