assistant_name: "0.8acc_alwaysnormalconf_mean0.8stdev0.05"
assistant_correctness:
  distribution_name: "bernoulli"
  params:
    p: 0.8
confidence_when_correct:
  distribution_name: "normal"
  params:
    mean: 0.8
    stdev: 0.05
confidence_when_incorrect:
  distribution_name: "normal"
  params:
    mean: 0.8
    stdev: 0.05
