assistant_name: "0.8acc_alwaysuniformconf_linguisticexpression"

assistant_correctness:
  distribution_name: "bernoulli"
  params:
    p: 0.8

confidence_when_correct:
  distribution_name: "uniform"
  params:
    low: 0.0
    high: 1.0
confidence_when_incorrect:
  distribution_name: "uniform"
  params:
    low: 0.0
    high: 1.0

confidence_expression: "quintiled_linguistic"   # "percentage" or "quintiled_linguistic"