assistant_name: "0.5acc_uniformconf"
#assistant_name: "0.5acc_alwaysuniformconf_quintiledlinguistic"
#assistant_name: "0.5acc_alwaysuniformconf_humanreadablestatement"

assistant_correctness:
  distribution_name: "bernoulli"
  params:
    p: 0.5

confidence_when_correct:
  distribution_name: "uniform"
  params:
    low: 0.0
    high: 1.0
confidence_when_incorrect:
  distribution_name: "uniform"
  params:
    low: 0.0
    high: 1.0

llm:
  llm_config_path: "configs/llm_configs/llama3_8b_instruct.yaml"
  generation_params:
    temperature: 0.5
    top_p: 0.95
    length_penalty: 1.0

confidence_expression: "percentage"   # "percentage" or "quintiled_linguistic" or "human_readable_linguistic_expression"