assistant_name: "0.5acc_corr:beta6a2b_incorr:beta5a5b"
assistant_correctness:
  distribution_name: "bernoulli"
  params:
    p: 0.5
confidence_when_correct:
  distribution_name: "beta"
  params:
    a: 6
    b: 2
confidence_when_incorrect:
  distribution_name: "beta"
  params:
    a: 5
    b: 5
confidence_expression: "percentage"
