assistant_name: "0.5acc_corr:beta12a3b_incorr:beta6a2b"
assistant_correctness:
  distribution_name: "bernoulli"
  params:
    p: 0.5
confidence_when_correct:
  distribution_name: "beta"
  params:
    a: 12
    b: 3
confidence_when_incorrect:
  distribution_name: "beta"
  params:
    a: 6
    b: 2
confidence_expression: "percentage"
