assistant_name: "0.5acc_corr:beta5a5b_incorr:beta2a6b"
assistant_correctness:
  distribution_name: "bernoulli"
  params:
    p: 0.5
confidence_when_correct:
  distribution_name: "beta"
  params:
    a: 5
    b: 5
confidence_when_incorrect:
  distribution_name: "beta"
  params:
    a: 2
    b: 6
confidence_expression: "percentage"
