assistant_name: "0.5acc_corr:beta4a2b_incorr:beta4a9b"
assistant_correctness:
  distribution_name: "bernoulli"
  params:
    p: 0.5
confidence_when_correct:
  distribution_name: "beta"
  params:
    a: 4
    b: 2
confidence_when_incorrect:
  distribution_name: "beta"
  params:
    a: 4
    b: 9
confidence_expression: "percentage"
